export const constants = {
	buttons: {
		cart: "Корзина",
		choose: "Выбрать",
		enter: "Войти",
		exit: "Выйти",
		end: "Конец",
		favourite: "Избранное",
		inCart: "В корзину",
		minus: "-",
		next: ">>",
		order: "Заказать",
		placeOrder: "Оформить заказ",
		plus: "+",
		previous: "<<",
		registration: "Регистрация",
		start: "Начало",
	},
	cities: {
		brest: "Брест",
		gomel: "Гомель",
		grodno: "Гродно",
		minsk: "Минск",
		mogilev: "Могилев",
		vitebsk: "Витебск",
	},
	card: {
		measurement: "Цена за 1 кг",
	},
	cartPage: {
		emptyBasket: "Корзина пуста",
		totalSum: "Итого к оплате:",
	},
	contacts: {
		address: "г. Минск, ул. Радиальная 56",
		mail: "cosinuts@gmail.com",
		phones: {
			mts: "+375 (33) 111-11-11",
			velcom: "+375 (44) 222-22-22",
		},
	},
	counter: {
		inCart: "В корзине",
	},
	entrance: {
		authEnter: "Войдите в аккаунт",
		authRegister: "Зарегистрируйте аккаунт",
		enter: "Войти",
		register: "Зарегистрироваться",
		useAccount: "Использовать существующий аккаунт",
	},
	errors: {
		profileExit: "Что-то пошло не так...",
	},
	measurement: {
		kilo: "кг",
	},
	notFoundPage: {
		error: "404",
		message: "Похоже, мы не можем найти нужную вам страницу...",
		return: "Перейти на главную",
	},
	orderForm: {
		labelBuilding: "Корпус",
		labelСash: "наличными при получении",
		labelСard: "банковской картой при получении",
		labelСity: "Город",
		labelСookie:
			"Мы используем файлы Cookie для улучшения работы, персонализации и повышения удобства пользования нашим сайтом.",
		labelСourier: "доставка курьером",
		labelCourierPostOfice: "доставка курьером Белпочты",
		labelEntrance: "Подъезд",
		labelEpos: "онлайн-платёж e-Pos",
		labelErip: "онлайн-платёж через систему ЕРИП",
		labelFlat: "Квартира",
		labelFloor: "Этаж",
		labelHouse: "Дом",
		labelPhone: "Телефон",
		labelName: "ФИО",
		labelPickup: "самовывоз",
		labelPostOfice: "доставка до отделения Белпочты",
		labelStreet: "Улица",
		required: "поля обязательные для заполнения",
		titleContacts: "Контактные данные",
		titleDelivery: "Способ доставки",
		titlePayment: "Способ оплаты",
	},
	orderList: {
		title: "Ваш заказ",
		totalSum: "Итого к оплате:",
	},
	orderPage: {
		orderPlaced: "Ваш заказ успешно оформлен!",
		title: "Оформление заказа",
	},
	pages: {
		about: "О нас",
		catalog: "Каталог",
		contacts: "Контакты",
		delivery: "О доставке",
		main: "Главная",
		stores: "Магазины",
	},
	placeholders: {
		building: "Введите номер корпуса",
		entrance: "Введите номер подъезда",
		flat: "Введите номер квартиры",
		floor: "Введите номер этажа",
		house: "Введите номер дома",
		name: "Введите ФИО",
		phone: "Введите номер телефона",
		search: "Поиск товаров",
		street: "Введите название улицы",
	},
	productPage: {
		measurement: "Цена за 1 кг",
	},
	routes: {
		about: "/about",
		cart: "/cart",
		catalog: "/catalog",
		contacts: "/contacts",
		delivery: "/delivery",
		main: "/",
		notFound: "*",
		order: "/order",
		product: "/catalog/:url/:id",
		products: "/catalog/:url",
		profile: "/profile",
		search: "/search",
		stores: "/stores",
	},
	searchPage: {
		notFound: "По выбранным Вами условиям товаров не найдено!",
	},
	socials: {
		altFacebook: "facebook",
		altInstagram: "instagram",
		altTelegram: "telegram",
		altTwitter: "twitter",
		altWhatsapp: "whatsapp",
		altYoutube: "youtube",
		refFacebook: "https://facebook.com/",
		refInstagram: "https://www.instagram.com/",
		refTelegram: "https://web.telegram.org/",
		refTwitter: "https://twitter.com/",
		refWhatsapp: "https://www.whatsapp.com/",
		refYoutube: "https://www.youtube.com/",
	},
	stores: {
		delivery: "бесплатная доставка по Минску при заказе от 50 рублей",
		deliveryTime:
			"доставка осуществляется с 09:00 до 21:00 с понедельника по пятницу",
		pickup: "пункты самовывоза в 10 городах РБ",
		workingHours: "время работы: ПН-ПТ 08:00 - 16:30",
	},
	symbols: {
		star: "*",
	},
	texts: {
		main: "Здоровое питание для здоровой жизни! Большой ассортимент орехов и сухофруктов по лучшим ценам!",
	},
	titles: {
		cart: "Корзина",
		catalog: "Наш ассортимент",
		category: "Категории товаров",
		profile: "Личный кабинет",
		search: "Поиск",
	},
	validation: {
		errorName: "Заполните поле ФИО",
		errorPhone: "Заполните поле телефон",
		errorStreet: "Заполните поле улица",
		errorHouse: "Заполните поле номер дома",
	},
};
